name: Build Windows Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4  # Обновили до v4
      with:
        submodules: recursive

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - name: Build Binary
      run: cargo build --release --verbose

    - name: Prepare Artifact
      run: |
        mkdir release
        copy target\release\magnum.exe release\magnum.exe
        copy README.md release\README.txt
        xcopy /E /I vendor release\vendor

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # Обновили до v4
      with:
        name: magnum-windows-bundle
        path: release/
